services:

  hello-vue-one:
    ports:
        - "180:80"
    networks:
      - hello-network
    build:
      context: hello-vue
      target: production
      args:
        ARG_FROM_COMPOSE_ONE: http://localhost/api1/
        ARG_FROM_COMPOSE_TWO: http://localhost/api2/
    depends_on:
        - hello-api-one
        - hello-api-two

  hello-vue-two:
    ports:
        - "181:80"
    networks:
      - hello-network
    build:
      context: hello-vue
      target: production
      args:
        ARG_FROM_COMPOSE_ONE: http://localhost/api1/
        ARG_FROM_COMPOSE_TWO: http://localhost/api2/
    depends_on:
        - hello-vue-one

  hello-reverse-proxy:
    image: nginx:stable
    ports:
      - "800:800"
    networks:
      - hello-network
    volumes:
      - ./conf.d:/etc/nginx/conf.d

#  check merged content: `docker compose -f docker-compose.yaml -f docker-compose-vue.yaml config`