services:

  hello-vue-one:
    ports:
        - "180:80"
    networks:
      - hello-network
    build:
      context: hello-vue
      target: production
      args:
        ARG_FROM_COMPOSE_ONE: http://localhost/api1
        ARG_FROM_COMPOSE_TWO: http://localhost/api2
    depends_on:
        - hello-api-one
        - hello-api-two

  hello-vue-two:
    ports:
        - "181:80"
    networks:
      - hello-network
    build:
      context: hello-vue
      target: production
      args:
        ARG_FROM_COMPOSE_ONE: http://localhost/api2
        ARG_FROM_COMPOSE_TWO: http://localhost/api1
    depends_on:
        - hello-api-one
        - hello-api-two

  hello-reverse-proxy:
    image: nginx:stable
    ports:
      - "80:80"
    networks:
      - hello-network
    volumes:
      - ./hello-nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - hello-vue-one
      - hello-vue-two
      - hello-api-one
      - hello-api-two

#  check merged content: `docker compose -f docker-compose.yaml -f docker-compose-vue.yaml config`